# .NET

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:  
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:
  - script: dotnet build Ginger/GingerCoreNETUnitTest/GingerCoreNETUnitTest.csproj 
  - script: dotnet build Ginger/GingerCoreCommonTest/GingerCoreCommonTest.csproj
  - script: dotnet test  Ginger/Ginger.sln --configuration $(buildConfiguration) --logger trx
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

- job: Windows
  pool:
    vmImage: 'vs2017-win2017'
  variables:  
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:
  - script: dotnet build Ginger/GingerCoreNETUnitTest/GingerCoreNETUnitTest.csproj 
  - script: dotnet build Ginger/GingerCoreCommonTest/GingerCoreCommonTest.csproj
  - script: dotnet test  Ginger/Ginger.sln --configuration $(buildConfiguration) --logger trx
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

