
jobs:

# ------------------------------------------------------------------------------------------------------
# Request Linux Ubunto 16.04 VM 
# ------------------------------------------------------------------------------------------------------
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

# ------------------------------------------------------------------------------------------------------
# Job Variables
# ------------------------------------------------------------------------------------------------------
  variables:  
    solution: '**/*.sln'     # = /home/vsts/work/1/s/Ginger
    buildConfiguration: 'Release'     
    # artifactsFolder: 'D:\a\1\a' 
  
  steps:
  

  - script: dotnet test  Ginger/GingerCoreCommonTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerCoreCommonTest'

  - script: dotnet test  Ginger/GingerCoreNETUnitTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerCoreNETUnitTest'

  - script: dotnet test  Ginger/GingerPluginCoreTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerPluginCoreTest'


    

  - task: PublishTestResults@2
    displayName: Publish test result
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

