# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:


- script: dotnet test  Ginger/GingerCoreCommonTest --configuration $(buildConfiguration) --logger trx
  displayName: 'Testing GingerCoreCommonTest'

- script: dotnet test  Ginger/GingerCoreNETUnitTest --configuration $(buildConfiguration) --logger trx
  displayName: 'Testing GingerCoreNETUnitTest'

- script: dotnet test  Ginger/GingerPluginCoreTest --configuration $(buildConfiguration) --logger trx
  displayName: 'Testing GingerPluginCoreTest'

- script: dotnet test  Ginger/GingerConsoleTest --configuration $(buildConfiguration) --logger trx
  displayName: 'Testing GingerConsoleTest'

- script: dotnet test  Ginger/GingerAutoPilotTest --configuration $(buildConfiguration) --logger trx
  displayName: 'Testing GingerAutoPilotTest'
    

- task: PublishTestResults@2
  displayName: Publish test result
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

