# .NET

jobs:


- job: Windows
  pool:
   vmImage: 'vs2017-win2016'
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU' 
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:

  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'  
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "D:\a\1\s\Ginger\**\bin\**Test**.dll" /TestCaseFilter:TestCategory=Level1 /Logger:trx
  - script: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "D:\a\1\s\Ginger\**\bin\**Test**.dll" /TestCaseFilter:TestCategory=Level2 /Logger:trx
  - script: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "D:\a\1\s\Ginger\**\bin\**Test**.dll" /TestCaseFilter:TestCategory=Level3 /Logger:trx
 
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

