# .NET

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:  
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:
  - script: dotnet test  Ginger/Ginger.sln --configuration $(buildConfiguration) --logger trx
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

- job: Windows
  pool:
   vmImage: 'vs2017-win2016'
  variables:  
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:

  - task: VSBuild@1
    inputs:
     solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "Unit Tests\bin\Debug\UnitTests.dll" /TestCaseFilter:TestCategory=Level1

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

