# .NET

jobs:


- job: Windows
  pool:
   vmImage: 'vs2017-win2016'
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU' 
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:

  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'  
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: dotnet vstest "D:\a\1\s\Ginger\GingerCoreCommonTest\bin\$(buildConfiguration)\netcoreapp2.1\GingerCoreCommonTest.dll" /TestCaseFilter:TestCategory=Level3 /Logger:trx




  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

