# .NET

jobs:


- job: Windows
  pool:
   vmImage: 'vs2017-win2016'
  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU' 
    buildConfiguration: 'Release'
    solutionDIrectory:  'Ginger-Automation/Ginger'
  steps:

  - task: NuGetToolInstaller@0
  - script: echo AFTER NuGetToolInstaller

  - task: NuGetCommand@2
    inputs:
      command: restore  
      restoreSolution: '$(solution)'  
  - script: echo BEFORE VSBuild 
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  - script: echo BEFORE Unit test
  - script: dotnet test "D:\a\1\s\Ginger\GingerCoreCommonTest\bin\$(buildConfiguration)\netcoreapp2.1\GingerCoreCommonTest.dll" /TestCaseFilter:TestCategory=Level1 /Logger:trx
  - script: echo AFTER Unit test




  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  - task: PublishBuildArtifacts@1

