
jobs:

# ------------------------------------------------------------------------------------------------------
# Request latest Ubunto/Linux
# ------------------------------------------------------------------------------------------------------
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

# ------------------------------------------------------------------------------------------------------
# Job Variables
# ------------------------------------------------------------------------------------------------------
  variables:  
    solution: '**/*.sln'     # = /home/vsts/work/1/s/Ginger
    buildConfiguration: 'Release'     
    # artifactsFolder: 'D:\a\1\a' 
  
  steps:
  
  - script: dotnet test  Ginger/GingerUtilsTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerUtilsTest'

  - script: dotnet test  Ginger/GingerCoreCommonTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerCoreCommonTest'

  - script: dotnet test  Ginger/GingerCoreNETUnitTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerCoreNETUnitTest'

  - script: dotnet test  Ginger/GingerPluginCoreTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerPluginCoreTest'

  - script: dotnet test  Ginger/GingerConsoleTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerConsoleTest'

  - script: dotnet test  Ginger/GingerAutoPilotTest --configuration $(buildConfiguration) --logger trx
    displayName: 'Testing GingerAutoPilotTest'
    

  - task: PublishTestResults@2
    displayName: Publish test result
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

# ------------------------------------------------------------------------------------------------------
# Package Test Artifacts
# ------------------------------------------------------------------------------------------------------


  - task: PowerShell@2
    displayName: Package test artifacts
    inputs:
      filePath: PackageTestArtifacts.ps1
    condition: succeededOrFailed()




# ------------------------------------------------------------------------------------------------------
# Publish Test Artifacts
# ------------------------------------------------------------------------------------------------------

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
